<a href="https://colab.research.google.com/github/Usmanimaaz12/Machine-Learning/blob/main/Data_Analytics_CLASS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import numpy as np

In [94]:
np.array([3.2,4,8.1,6,2])

array([3.2, 4. , 8.1, 6. , 2. ])

In [95]:
np.array([1,2,3,4,5],dtype="str")

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [96]:
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [97]:
np.zeros((5,6),dtype="float")

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [98]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [99]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [100]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [101]:
np.random.random((3,3))

array([[0.31465264, 0.08895385, 0.45218975],
       [0.04014796, 0.61249877, 0.13314131],
       [0.94241649, 0.78014864, 0.87498714]])

In [102]:
np.random.normal(0,1,(3,3))

array([[-0.41365356, -0.36219941, -0.59712416],
       [-0.38776965, -1.12516094,  0.36559245],
       [-0.01493524, -0.47018137, -0.55983453]])

In [103]:
np.random.randint(0,10,(3,3))

array([[5, 2, 9],
       [1, 0, 6],
       [2, 8, 5]])

In [104]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [105]:
np.empty((3,3),dtype="int")

array([[4607182418800017408,                   0,                   0],
       [                  0, 4607182418800017408,                   0],
       [                  0,                   0, 4607182418800017408]])

In [106]:
np.zeros(10,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [107]:
x1=np.random.randint(10,size=6)

In [108]:
x2=np.random.randint(10,size=(3,4))

In [109]:
x3=np.random.randint(10,size=(3,4,5))


In [110]:
x1

array([3, 7, 0, 1, 4, 5])

In [111]:
x2

array([[3, 1, 7, 9],
       [1, 9, 1, 3],
       [2, 4, 9, 8]])

In [112]:
x3

array([[[6, 7, 0, 7, 3],
        [4, 6, 4, 1, 5],
        [0, 2, 2, 6, 9],
        [4, 7, 9, 6, 9]],

       [[1, 9, 0, 7, 9],
        [7, 3, 1, 4, 8],
        [5, 7, 9, 6, 7],
        [6, 7, 1, 3, 9]],

       [[1, 8, 5, 7, 2],
        [3, 1, 2, 9, 1],
        [1, 2, 1, 1, 5],
        [8, 4, 8, 3, 3]]])

In [113]:
print(x3.ndim)

3


In [114]:
print(x3.shape)


(3, 4, 5)


In [115]:
print(x1.size)

6


In [116]:
print(x1.dtype)

int64


In [117]:
print(x1.itemsize)

8


In [118]:
print(x1.nbytes)

48


In [119]:
print(x2.dtype)

int64


In [120]:
x2.itemsize

8

In [121]:
x1
x2

array([[3, 1, 7, 9],
       [1, 9, 1, 3],
       [2, 4, 9, 8]])

In [122]:
x1

array([3, 7, 0, 1, 4, 5])

In [123]:
x2[2,1]

4

In [124]:
x1[0]

3

In [125]:
x1[0]=4.1452

In [126]:
x1

array([4, 7, 0, 1, 4, 5])

In [127]:
x=np.arange(0,10)

In [128]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
x[::2]

array([0, 2, 4, 6, 8])

In [130]:
x[1::2]

array([1, 3, 5, 7, 9])

In [131]:
x[-4:-2:1]

array([6, 7])

In [132]:
x[-1:-2:1]

array([], dtype=int64)

In [133]:
x2[:2,:3]

array([[3, 1, 7],
       [1, 9, 1]])

In [134]:
x2

array([[3, 1, 7, 9],
       [1, 9, 1, 3],
       [2, 4, 9, 8]])

In [135]:
x2[:3,::2]

array([[3, 7],
       [1, 1],
       [2, 9]])

In [136]:
x2[::-1,::-1]

array([[8, 9, 4, 2],
       [3, 1, 9, 1],
       [9, 7, 1, 3]])